In [1]:
#import data
import pandas as pd

df_spam = pd.read_csv('/content/spam.csv')
display(df_spam.head())

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
#import required libraries
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [3]:
#load data without errors
df = pd.read_csv("spam.csv", encoding='latin-1')
display(df.head())

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
#keeps only the usefull collums
df = df[['Category', 'Message']]
df.columns = ['label', 'message']
display(df.head())

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
#convert labels to numbers
df['label'] = df['label'].map({'ham': 0, 'spam': 1})
display(df.head())

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [6]:
#define features and targets
X = df['message']
y = df['label']

In [7]:
#split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [18]:
#convert text to numbers
vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

print(f"Shape of vectorized training data: {X_train_vectorized.shape}")
print(f"Shape of vectorized testing data: {X_test_vectorized.shape}")

Shape of vectorized training data: (4457, 7733)
Shape of vectorized testing data: (1115, 7733)

In [19]:
# Train a Multinomial Naive Bayes classifier
model = MultinomialNB()
model.fit(X_train_vectorized, y_train)

print("Model training complete.")

Model training complete.

In [20]:
# Train a Multinomial Naive Bayes classifier
model = MultinomialNB()
model.fit(X_train_vectorized, y_train)

print("Model training complete.")

Model training complete.

In [21]:
# Make predictions on the test set
y_pred = model.predict(X_test_vectorized)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("Classification Report:")
print(report)

Accuracy: 0.9928
Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       966
           1       1.00      0.95      0.97       149

    accuracy                           0.99      1115
   macro avg       1.00      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

In [22]:
#test
y_pred = model.predict(X_test_vectorized)
print("First 5 predictions:")
print(y_pred[:5])

First 5 predictions:
[0 0 0 0 0]

In [23]:
#Accuracy score
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.9928251121076234

Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       966
           1       1.00      0.95      0.97       149

    accuracy                           0.99      1115
   macro avg       1.00      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

In [24]:
#testmail
sample = ["Congratulations! You won a free ticket. Call now!"]

sample_transformed = vectorizer.transform(sample)
prediction = model.predict(sample_transformed)

print("Prediction:", "Spam" if prediction[0] == 1 else "Not Spam")

Prediction: Spam

In [25]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Data split into training and testing sets.")

Data split into training and testing sets.

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

# Convert text messages to numerical feature vectors using CountVectorizer
vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

print(f"Shape of vectorized training data: {X_train_vectorized.shape}")
print(f"Shape of vectorized testing data: {X_test_vectorized.shape}")

Shape of vectorized training data: (4457, 7733)
Shape of vectorized testing data: (1115, 7733)

In [27]:
from sklearn.naive_bayes import MultinomialNB

# Train a Multinomial Naive Bayes classifier with the vectorized data
model = MultinomialNB()
model.fit(X_train_vectorized, y_train)

print("Model training complete with vectorized data.")

Model training complete with vectorized data.

In [28]:
# Generate a random email text for testing
random_email_text = "Win a free iPhone now! Click here to claim your prize. Limited time offer!"

print(f"Testing email: '{random_email_text}'")

# Transform the random email text using the trained vectorizer
random_email_transformed = vectorizer.transform([random_email_text])

# Make a prediction using the trained model
random_email_prediction = model.predict(random_email_transformed)

# Print the prediction result
print("Prediction for random email:", "Spam" if random_email_prediction[0] == 1 else "Not Spam")

Testing email: 'Win a free iPhone now! Click here to claim your prize. Limited time offer!'
Prediction for random email: Spam